CREATE TABLE TEMPP(STRING1 VARCHAR(25),
STRING2 VARCHAR(25),
RESULT VARCHAR(25));

DELIMITER //
CREATE PROCEDURE PROC1()
BEGIN
DECLARE RES VARCHAR(20);
DECLARE STRING1 VARCHAR(25) DEFAULT 'DAC';
DECLARE STRING2 VARCHAR(25) DEFAULT 'CDAC';
IF
STRING1(SUBSTR(STRING2='DAC'))
INSERT INTO TEMPP VALUES(STRING1,STRING2,RES);
END IF ;
END; //
DELIMITER ; 
CALL PROC1();
DROP PROCEDURE PROC1;